dataset = [
    {"input": "Hey, how's it going?", "output": "Yo, pretty chill! What's up with you?"},
    {"input": "What's the weather like today?", "output": "Sunny with a high of 75°F. Perfect day to go outside!"},
    {"input": "Can you recommend a good book?", "output": "Sure, 'The Alchemist' by Paulo Coelho is a great read!"},
    {"input": "I'm feeling a bit down today.", "output": "Aw, sorry to hear that. Wanna talk about it or maybe hear a joke?"},
    {"input": "Tell me a fun fact!", "output": "Did you know octopuses have three hearts and can change color to blend in?"},
    {"input": "How do I make a sandwich?", "output": "Grab bread, spread mayo or mustard, add lettuce, tomato, cheese, and your favorite meat. Done!"},
    {"input": "What's your favorite movie?", "output": "I dig 'Inception'—mind-bending stuff! What's yours?"},
    {"input": "Can you help me with math?", "output": "Of course! What's the problem you're stuck on?"},
    {"input": "Why is the sky blue?", "output": "Rayleigh scattering: shorter blue light waves scatter more in the atmosphere. Cool, right?"},
    {"input": "I'm bored. Any ideas?", "output": "Try learning a new skill on YouTube or binge a new series. Got a hobby you like?"},
    {"input": "What's the capital of France?", "output": "That’s Paris, my friend!"},
    {"input": "How do I stay motivated?", "output": "Set small goals, celebrate wins, and remind yourself why you started. You got this!"},
    {"input": "Tell me a joke!", "output": "Why did the scarecrow become a motivational speaker? He was outstanding in his field!"},
    {"input": "What's for dinner?", "output": "How about some pasta with marinara sauce? Quick and tasty!"},
    {"input": "Can you explain AI in simple terms?", "output": "AI is like a super smart computer that learns from data to do tasks, like chatting or recognizing images."},
    {"input": "What's the best way to learn coding?", "output": "Start with Python, use free resources like Codecademy, and build small projects to practice."},
    {"input": "I lost my keys. Any tips?", "output": "Retrace your steps, check pockets, and look in unusual spots like drawers. Good luck!"},
    {"input": "What's your favorite color?", "output": "I’m vibing with electric blue. You got a fave?"},
    {"input": "How do I fix a slow laptop?", "output": "Clear disk space, update software, and maybe add more RAM if you can. Need specifics?"},
    {"input": "What's the meaning of life?", "output": "Big question! Some say it’s finding purpose or happiness. What do you think?"},
    {"input": "Can you write a short poem?", "output": "Moonlight glows, soft winds sigh, / Stars above whisper why."},
    {"input": "How do I make coffee?", "output": "Grind beans, add to a filter, pour hot water through, and enjoy your brew!"},
    {"input": "What's a good workout routine?", "output": "Try 30 min of cardio, 15 min of strength training, and stretch daily. Mix it up!"},
    {"input": "I'm nervous about a presentation.", "output": "Practice out loud, know your stuff, and breathe deep. You’ll crush it!"},
    {"input": "What's the tallest mountain?", "output": "Mount Everest, standing at 8,848 meters. A beast!"},
    {"input": "How do I save money?", "output": "Budget with the 50/30/20 rule: 50% needs, 30% wants, 20% savings. Track spending!"},
    {"input": "What's a good gift for a friend?", "output": "Something personal, like a custom mug or a book they’d love. What’s their vibe?"},
    {"input": "Can you sing a song?", "output": "I can’t sing, but I can write one! Want some lyrics instead?"},
    {"input": "How do I improve my memory?", "output": "Use mnemonics, practice recall, and get enough sleep. Brain games help too!"},
    {"input": "What's the best pizza topping?", "output": "Pepperoni for the win! What’s your go-to?"},
    {"input": "How do I start a blog?", "output": "Pick a niche, use WordPress or Medium, and post consistently. Share on social media!"},
    {"input": "What's a good morning routine?", "output": "Wake early, hydrate, meditate for 5 min, and plan your day. Sets a great tone!"},
    {"input": "Can you tell me about dinosaurs?", "output": "Dinosaurs ruled 230–66 million years ago. T-Rex was a fierce predator; Brontosaurus, a giant herbivore."},
    {"input": "How do I deal with stress?", "output": "Try deep breathing, exercise, or journaling. Talking to someone helps too!"},
    {"input": "What's your favorite animal?", "output": "I’m all about pangolins—those scaly cuties! What’s yours?"},
    {"input": "How do I learn a new language?", "output": "Use apps like Duolingo, practice daily, and try speaking with natives. Immersion’s key!"},
    {"input": "What's the best way to apologize?", "output": "Be sincere, own your mistake, and say how you’ll make it right. Mean it!"},
    {"input": "Can you help me plan a trip?", "output": "Sure! Where to? I can suggest spots, budgets, or itineraries."},
    {"input": "What's the fastest animal?", "output": "Peregrine falcon, diving at 240 mph. Insane speed!"},
    {"input": "How do I stay organized?", "output": "Use a planner, make to-do lists, and declutter your space weekly. Systems work!"},
    {"input": "What's a good hobby to pick up?", "output": "Photography’s fun and creative. Start with your phone! Any interests?"},
    {"input": "How do I make friends?", "output": "Be open, join clubs or events, and just start small talks. Genuine vibes attract people!"},
    {"input": "What's the biggest planet?", "output": "Jupiter, with a diameter of 139,820 km. It’s massive!"},
    {"input": "How do I improve my writing?", "output": "Write daily, read a lot, and get feedback. Clarity and practice are key!"},
    {"input": "What's a good dessert recipe?", "output": "Chocolate chip cookies: flour, sugar, butter, eggs, and chips. Bake at 375°F for 10 min!"},
    {"input": "How do I stay healthy?", "output": "Eat balanced, exercise 3–4 times a week, sleep 7–8 hours, and drink water."},
    {"input": "What's the deepest ocean?", "output": "Pacific Ocean, with the Mariana Trench at 11,000 meters deep."},
    {"input": "How do I boost confidence?", "output": "Set small wins, practice self-talk, and face fears step-by-step. You’re awesome!"},
    {"input": "What's a good party game?", "output": "Codenames—easy, fun, and gets everyone talking. Tried it?"},
    {"input": "How do I manage time better?", "output": "Prioritize tasks, use a calendar, and avoid multitasking. Focus on one thing at a time!"},
]


import json

with open("chat_dataset.json", "w") as f:
    json.dump(dataset, f, indent=2)